# mysql:
#     host: localhost
#     dbname: db
#     user: user
#     passwd: pwb
#     port: 3306

sqlite:
  url: sqlite:///db/sqlite/wikitable.db

OPENAI:
  api_key: "ollama"
  model: "llama3.3:70b"
  base_url: "http://localhost:11434/v1"
  temperature: 0.01
  max_retries: 5
  request_timeout: 6000

